### ISSUE TITLE
帅哥，你还维护嘛，现在最新版本MAC安装不了了……

### ISSUE THREAD

**Issue by s5s5** [huangzhaolin/myssh#2]
最新版本MAC安装不了了……

**Comment by huangzhaolin** [comment]
哈哈，你要不把错误发一下，我看看

**Comment by s5s5** [comment]
https://github.com/AJSoft/myssh
我照这哥们的弄好了
他好像给你贡献了代码，
https://github.com/huangzhaolin/myssh/pull/1
你审核合并下应该就好了
